### ISSUE TITLE
Support [[gsl::lifetime_out(param)]]

### ISSUE THREAD

**Issue by mgehre** [mgehre/llvm-project#23]
To make a parameter or `this` an output-only, i.e. do not validate the deref in caller, and initialize the deref to (invalid) in callee.

**Comment by Xazax-hun** [comment]
Note that, the current spelling is `[[gsl::lifetime_out(param)]]`.

**Comment by mgehre** [comment]
I don't quite understand what is left to do on this issue. If you know it, please re-open / create a more specific new one.

**Comment by Xazax-hun** [comment]
We do not support `gsl::lifetime_out`, at least I did not find any traces of it in the code. What is the reason we closed this?

Note that, if we only treat pointees of references as output by default we need both `lifetime_out` and `lifetime_in` to make it possible for the users to mark arguments accordingly.

**Comment by Xazax-hun** [comment]
Should be implemented in https://github.com/mgehre/llvm-project/commit/bf0a12eb45ea0546b04984d17ceac6516ac62577
