### ISSUE TITLE
Diagnose statement-local with ternary operator

### ISSUE THREAD

**Issue by mgehre** [mgehre/llvm-project#30]
```
#include <string>
#include <string_view>

void f(bool cond) {
    std::string def = "default";
    std::string_view v = cond ? def : ""; // should diagnose because "" is converted to a temporary std::string.
}
```

https://godbolt.org/z/X1iULO

**Comment by Xazax-hun** [comment]
I do get the warning for this test-case using the top of lifetime branch. Maybe this is due to something not being categorized right on upstream yet?

**Comment by mgehre** [comment]
My PR for compiler explorer was merged, but the site still shows the old version. We should still add this test case to test/Sema/warn-lifetime-analysis-nocfg.cpp.

**Comment by Xazax-hun** [comment]
Agreed!

**Comment by Xazax-hun** [comment]
Test added.
