### ISSUE TITLE
gsl::Owner/Pointer not propagated to classTemplateSpecializationDecl if added late

### ISSUE THREAD

**Issue by mgehre** [mgehre/llvm-project#41]
In the case
```
template<class T>
class C;

template<class T>
class C {};

template<class T>
class [[gsl::Owner]] C;

static_assert(sizeof(C<int>), ""); // Force instantiation.
```
`C<int>` will not have the [[gsl::Owner]] attribute, because we added it to the canonical decl of the templated record, but the definition (!= canonical decl) is used for instantiations.

@Xazax-hun: Should we add the OwnerAttr/PointerAttr to all declarations instead of just the canonical? Clang will automatically take care of later redecl which inherit attributes from the previous decl.

**Comment by Xazax-hun** [comment]
I am not opposed to adding Owner/Pointer to all the declarations, but I have concerns about the function annotations. Those annotations can grow really big due to all the information they have. Attaching them to all the decls will make the AST dumps quite a lot bigger too. And I wonder if we might have similar issues with function templates + definitions.

**Comment by Xazax-hun** [comment]
Nice work finding the root cause here!

**Comment by mgehre** [comment]
If we have code like this
```
template<class T>
class [[gsl::Owner]] C;

template<class T>
class C {};

template<class T>
class C;

static_assert(sizeof(C<int>), ""); // Force instantiation.
```
clang already puts the OwnerAttr on all decls, because we specified it as `InheritableAttr` in Attr.td (which seems to be the default for the majority of all attributes).

**Comment by mgehre** [comment]
Turns out that adding the attribute to all decls also fixes #32. And it simplifies the check for the attr, because we don't need to first go to the canonical.

**Comment by mgehre** [comment]
For function annotations, we might consider to share the (big) state among multiple attributes.

**Comment by Xazax-hun** [comment]
I do not know how attributes are copied, and state sharing should be feasible. But it does not solve the AST dump problem. It may not be a big concern though.

**Comment by mgehre** [comment]
45bee93a8a9036496db3ae91ce08d44e508826b2
