### ISSUE TITLE
Move statement-local warnings behind another flag

### ISSUE THREAD

**Issue by mgehre** [mgehre/llvm-project#50]
So they can be disabled separately, as requested by Richard. fyi @Xazax-hun

**Comment by mgehre** [comment]
@Xazax-hun Would you be able to move the rest of our statement-local warnings behind that flag? I'm not exactly sure about the logic yet.
Would we need to sprinkle `if(IsGslPtrInitWithGslTempOwner)` around `Diag(DiagLoc, diag::warn_ret_stack_addr_ref)` and other diags?

**Comment by Xazax-hun** [comment]
Yeah, unfortunately, they are not all behind the same flag, because there are some logic reused between all those warnings. I think I have something slightly different in mind.

**Comment by mgehre** [comment]
This is now partly implemented.
