### ISSUE TITLE
crash in compile w/-Wlifetime flag

### ISSUE THREAD

**Issue by WallStProg** [mgehre/llvm-project#68]
Hi again Matthias:

Got an error building with -Wlifetime enabled:

```
UNREACHABLE executed at /shared/buildtest/clang/10.0.0/llvm-project/clang/lib/Analysis/LifetimePsetBuilder.cpp:964!
```

[build.txt](https://github.com/mgehre/llvm-project/files/3714375/build.txt)

[msggen-555b4a.zip](https://github.com/mgehre/llvm-project/files/3714381/msggen-555b4a.zip)

**Comment by mgehre** [comment]
Fixed by 13b2292a
