### ISSUE TITLE
crash in clang::lifetime::VisitBlock

### ISSUE THREAD

**Issue by 0x8000-0000** [mgehre/llvm-project#86]
Crash with a simple program:

```
#include <array>
#include <cassert>
#include <iostream>
#include <limits>
#include <random>

namespace
{
[[nodiscard]] std::array<uintmax_t, 4> getTestValuesInRange(uintmax_t start, uintmax_t end, std::mt19937& randomEngine)
{
    assert(start <= end);
    return {start, end, (start + end) / 2, std::uniform_int_distribution<uintmax_t>{start, end}(randomEngine)};
}
}

int main()
{
   std::mt19937 randomEngine;

   const auto values = getTestValuesInRange(/* start = */ 1, /* end = */ 1024, randomEngine);
   for (const auto value : values)
   {
      std::cout << value << "\n";
   }

   std::cout << std::endl;

   return 0;
}
```

fldiag114 ~/work/snippets$ /opt/clang10/bin/clang++ -std=c++17 -Wlifetime -Wall -Werror test-life.cc
Stack dump:
0.      Program arguments: /opt/clang10/bin/clang-10 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard
-value-names -main-file-name test-life.cc -mrelocation-model static -mthread-model posix -mframe-pointer=all -fmath-errno -fno-rounding-math -masm-verbose -mc
onstructor-aliases -munwind-tables -target-cpu x86-64 -dwarf-column-info -fno-split-dwarf-inlining -debugger-tuning=gdb -resource-dir /opt/clang10/lib/clang/1
0.0.0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/x86_64
-linux-gnu/c++/9 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/x86_64-linux-gnu/c++/9 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/
9/../../../../include/c++/9/backward -internal-isystem /usr/local/include -internal-isystem /opt/clang10/lib/clang/10.0.0/include -internal-externc-isystem /u
sr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -Wlifetime -Wall -Werror -std=c++17 -fdeprecated-macro -
fdebug-compilation-dir /home/fiucha/work/snippets -ferror-limit 19 -fmessage-length 0 -fgnuc-version=4.2.1 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -f
diagnostics-show-option -fcolor-diagnostics -faddrsig -o /tmp/test-life-40a2de.o -x c++ test-life.cc
1.      test-life.cc:14:1: current parser token '}'
2.      test-life.cc:7:1: parsing namespace '(anonymous)'
3.      test-life.cc:10:1: parsing function body '(anonymous namespace)::getTestValuesInRange'
 #0 0x0000000001672de4 PrintStackTraceSignalHandler(void*) (/opt/clang10/bin/clang-10+0x1672de4)
 #1 0x0000000001670c4e llvm::sys::RunSignalHandlers() (/opt/clang10/bin/clang-10+0x1670c4e)
 #2 0x00000000016731dc SignalHandler(int) (/opt/clang10/bin/clang-10+0x16731dc)
 #3 0x00007f9ca839c890 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x12890)
 #4 0x00000000030ddf78 clang::StmtVisitorBase<llvm::make_const_ptr, clang::lifetime::(anonymous namespace)::PSetsBuilder, void>::Visit(clang::Stmt const*) (/o
pt/clang10/bin/clang-10+0x30ddf78)
 #5 0x00000000030dd91b clang::lifetime::VisitBlock(clang::FunctionDecl const*, std::map<clang::lifetime::Variable, clang::lifetime::PSet, std::less<clang::lif
etime::Variable>, std::allocator<std::pair<clang::lifetime::Variable const, clang::lifetime::PSet> > >&, llvm::Optional<std::map<clang::lifetime::Variable, cl
ang::lifetime::PSet, std::less<clang::lifetime::Variable>, std::allocator<std::pair<clang::lifetime::Variable const, clang::lifetime::PSet> > > >&, std::map<c
lang::Expr const*, clang::lifetime::PSet, std::less<clang::Expr const*>, std::allocator<std::pair<clang::Expr const* const, clang::lifetime::PSet> > >&, std::
map<clang::Expr const*, clang::lifetime::PSet, std::less<clang::Expr const*>, std::allocator<std::pair<clang::Expr const* const, clang::lifetime::PSet> > >&,
clang::CFGBlock const&, clang::lifetime::LifetimeReporterBase&, clang::ASTContext&, llvm::function_ref<bool (clang::QualType, clang::QualType)>) (/opt/clang10
/bin/clang-10+0x30dd91b)
 #6 0x00000000030ce8aa clang::lifetime::LifetimeContext::TraverseBlocks() (/opt/clang10/bin/clang-10+0x30ce8aa)

**Comment by 0x8000-0000** [comment]
I have tried to attach the pre-processed zip file but it seems the .5 MB file is too large for GitHub.

**Comment by 0x8000-0000** [comment]
Top commit:

```
commit 833333555992f4c7c8a7a0bdcb03262eccc430c2 (lifetime/lifetime)
Author: Gabor Horvath <xazax@google.com>
Date:   Fri Dec 27 16:02:19 2019 -0800
```

**Comment by Xazax-hun** [comment]
I will look into this, thanks!

**Comment by Xazax-hun** [comment]
Should be fixed now, thanks for reporting!
